### PR TITLE
Render memory plots

### PR DESCRIPTION
**Pull request by willGraham01**
For https://github.com/UCL/TLOmodel/issues/1355 |

Edits the "run statistics" page to display the captured memory statistics, which the profiling runs were previously capturing but not displaying.

Making this it's own PR as the "run statistics" page is starting to get a bit bloated - it has no internal navigation but scrolling through the plots is quite a chore.

- Could add a collapse option for each individual plot
- Could try adding a "contents" at the top to allow for quick navigation

Opinions on this welcome :smile: 

#### Stats we're now plotting

The following (plottable) statistics are being captured by the profiling run; and those with a checked box are currently being plotted (includes those added by this PR):

- [ ] "duration": 26804.275735139847, (Duration of the entire profiling run)
- [x] "cpu_time": 26801.766409699998,
- [ ] "disk_reads": 1465,
- [ ] "disk_writes": 63014,
- [x] "disk_read_MB": 79.811584,
- [x] "disk_write_MB": 832.028672,
- [x] "disk_read_s": 0.505,
- [x] "disk_write_s": 33.234,
- [x] "pop_df_rows": 62000,
- [x] "pop_df_cols": 444,
- [x] "pop_df_mem_MB": 115.898045, (Pop. dataframe size in memory)
- [x] "pop_df_times_extended": 12,

### CODE REVIEW

**Review by matt-graham — COMMENTED** [review]
Adding a table of contents at the beginning of page seems worthwhile as it [looks like](https://docutils.sourceforge.io/docs/ref/rst/directives.html#table-of-contents) this should just require adding something like
```
.. contents::
```
somewhere in the `.rst` file with the contents then automatically generated from the heading structure.

**Review by matt-graham — APPROVED** [review]

**Comment by willGraham01** [comment]
Have added the contents page - repo setting require an up-to-date review so sorry for notification noise :sweat_smile:

**Comment by tamuri** [comment]
> Opinions on this welcome

Take inspiration from craiglist - single line of anchor links across the top, pls.

**Comment by matt-graham** [comment]
Adding some custom CSS similar to

```css
#list-of-summary-statistics ul {
    list-style: none;
    padding: 0;
}

#list-of-summary-statistics li {
    display: inline;
    margin-right: 10px;
}

#list-of-summary-statistics li p {
    display: inline;
}
```

would make the list items displayed inline (the `li p` entry is needed as weirdly Sphinx seems to wrap the titles in the list items in a `p` tag for some reason), though still not on a single line as too many

image

I prefer the Sphinx default that @willGraham01 currently has though of items on separate lines as easier to scan through

**Review by matt-graham — APPROVED** [review]
Approving as looks good from my perspective but let's see if @tamuri thinks we should adjust contents styling.

**Comment by tamuri** [comment]
The Sphinx output is fine - thanks!

**Pull request merged**
